### ISSUE TITLE
Server GUI option pane error on Unix based systems

### ISSUE THREAD

**Issue by MatteoBosco89** [SmartRoomCorporation/SmartRoom#2] opened 2020-12-30 09:12 UTC
The Server GUI option pane cannot be closed once is opened. 

System: Raspbian GNU/Linux 10 (buster)

Stack Trace:
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/Desktop/SmartRoom/server/src/main/ServerGui/ServerGui.py", line 67, in configWindow
    self.window.wm_attributes("-disabled", True)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1788, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: bad attribute "-disabled": must be -alpha, -topmost, -zoomed, -fullscreen, or -type

**Comment by augusto196** [comment] 2020-12-30 09:18
i have the same issue on this system Mac OS Catalina version: 10.15.6 
The Traceback seems equal

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/patriziadecristofaro/GIT/SmartRoom/server/src/main/ServerGui/ServerGui.py", line 66, in configWindow
    self.window.wm_attributes("-disabled", True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1788, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: bad attribute "-disabled": must be -alpha, -fullscreen, -modified, -notify, -titlepath, -topmost, or -transparent

**Comment by SenselessMite** [comment] 2020-12-30 09:26
The problem arises because on windows systems is present the parameters -disabled for tkinter Tk. The issue is fixed in this commit: https://github.com/SmartRoomCorporation/SmartRoom/commit/730a034a0e4653c4711b8ddc27a47445d3c4628c

**Closed as completed by SenselessMite** 2020-12-30 09:26 UTC
